IC/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('products/', include('products.urls')),
    path('bag/', include('bag.urls')),
    path('checkout/', include('checkout.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('', views.all_products, name='products'),
    path('<product_id>', views.product_detail, name='product_detail')
]

checkout/models.py
import uuid

from django.db import models
from django.db.models import Sum
from django.conf import settings 

from products.models import Product

class Order(models.Model):
    order_number = models.CharField(max_length=32, null=False, editable=False)
    full_name = models.CharField(max_length=50, null=False, blank=False)
    email = models.EmailField(max_length=254, null=False, blank=False)
    phone_number = models.CharField(max_length=20, null=False, blank=False)
    country = models.CharField( max_length=40, null=False, blank=False)
    postcode = models.CharField(max_length=20, null=True, blank=True)
    town_or_city = models.CharField(max_length=40, null=False, blank=False)
    street_address1 = models.CharField(max_length=80, null=False, blank=False)
    street_address2 = models.CharField(max_length=80, null=True, blank=True)
    county = models.CharField(max_length=80, null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True)
    delivery_cost = models.DecimalField(max_digits=6, decimal_places=2, null=False, default=0)
    order_total = models.DecimalField(max_digits=10, decimal_places=2, null=False, default=0)
    grand_total = models.DecimalField(max_digits=10, decimal_places=2, null=False, default=0)

    def _generate_order_number(self):
        
        return uuid.uuid4().hex.upper()

    def update_total(self):
        self.order_total = self.lineitems.aggregate(Sum('lineitem_total'))['lineitem_total__sum'] or 0
        if self.order_total < settings.FREE_DELIVERY_THRESHOLD:
            self.delivery_cost = self.order_total * settings.STANDARD_DELIVERY_PERCENTAGE / 100
        else:
            self.delivery_cost = 0
        self.grand_total = self.order_total + self.delivery_cost
        self.save()

    def save(self, *args, **kwargs):

        if not self.order_number:
            self.order_number = self._generate_order_number()
        super().save(*args, **kwargs)


    def __str__(self):
        return self.order_number



class OrderLineItem(models.Model):
    order = models.ForeignKey(Order, null=False, blank=False, on_delete=models.CASCADE, related_name='lineitems')
    product = models.ForeignKey(Product, null=False, blank=False, on_delete=models.CASCADE)
    product_size = models.CharField(max_length=2, null=True, blank=True)
    quantity = models.IntegerField(null=False, blank=False, default=0)
    lineitem_total = models.DecimalField(max_digits=6, decimal_places=2, null=False, blank=False, editable=False)

    def save(self, *args, **kwargs):
        
        self.lineitem_total = self.product.price * self.quantity
        super().save(*args, **kwargs)
    
    def __str__(self):
        return f'SKU {self.product.sku} on order {self.order.order_number}'

products/models.py
from pickle import FALSE
from django.db import models

# Create your models here.
class Category(models.Model):

    class Meta:
        verbose_name_plural = 'Categories'

    name = models.CharField(max_length=254)
    friendly_name = models.CharField(max_length=254, null=True, blank=True)

    def __str__(self):
        return self.name
    
    def get_friendly_name(self):
        return self.friendly_name

class Product(models.Model):
    category = models.ForeignKey('Category', null=True, blank=True, on_delete=models.SET_NULL)
    sku = models.CharField(max_length=254, null=True, blank=True)
    name = models.CharField(max_length=254)
    description = models.TextField()
    price = models.DecimalField(max_digits=6, decimal_places=2)
    has_sizes = models.BooleanField(default=False, null=True, blank=True)
    rating = models.DecimalField(max_digits=6, decimal_places=2, null=True, blank=True)
    mainImage_url = models.URLField(max_length=1254, null=True, blank=True)
    Image_url2 = models.URLField(max_length=1254, null=True, blank=True)
    Image_url3 = models.URLField(max_length=1254, null=True, blank=True)
    main_image = models.ImageField(null=True, blank=True)
    image2 = models.ImageField(null=True, blank=True)
    image3 = models.ImageField(null=True, blank=True)

    def __str__(self):
        return self.name

products/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from .models import Product, Category
from django.contrib import messages
from django.db.models import Q
from django.db.models.functions import Lower

# Create your views here.
def all_products(request):
    products = Product.objects.all()
    categories = None
    query = None
    sort = None
    direction = None
    if request.GET:
        if 'sort' in request.GET:
            sortkey = request.GET['sort']
            sort = sortkey
            if sortkey == 'name':
                sortkey = 'lower_name'
                products = products.annotate(lower_name=Lower('name'))
            if sortkey == 'category':
                sortkey = 'category__name'
            if 'direction' in request.GET:
                direction = request.GET['direction']
                if direction == 'desc':
                    sortkey = f'-{sortkey}'
            products = products.order_by(sortkey)

        if 'categories' in request.GET:
            categories = request.GET['categories'].split(',')
            products = products.filter(category__name__in=categories)
            categories = Category.objects.filter(name__in=categories)

        if 'q' in request.GET:
            query = request.GET['q']
            if not query:
                messages.error(request,"You didnt enter anything in the search box!!")
                return redirect(reverse('products'))
            
            queries = Q(name__icontains=query) | Q(description__icontains=query)
            products = products.filter(queries)
    
    current_sorting = f'{sort}_{direction}'
    context = {
        'products' : products,
        'current_categories':categories,
        'search_term': query,
        'current_sorting': current_sorting,
    }
    return render(request, 'products/products.html', context)

def product_detail(request, product_id):
    product = get_object_or_404(Product, pk=product_id)

    context = {
        'product': product,
    }

    return render(request, 'products/product_details.html', context)

products/templates/products/product_details.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
<div class="container header-container">
    <div class="row">
        <div class="col">
            
        </div>
    </div>
</div>
{% endblock %}

{% block content %}

<div class="container my-3">
    <div class="row">
        <div class="col text-center">
            <h1>{{ product.name }}</h1>
        </div>
    </div>
</div>
<div class="container my-2">
    <div class="row bg-light">
        <div id="carouselExampleIndicators" class="carousel slide col-12 col-lg-6 my-auto" data-bs-ride="carousel">
            <div class="carousel-indicators">
                <li>
                    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
                    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
                    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
                </li>
            </div>
            
            <div class="carousel-inner">
                <div class="carousel-item active" style="height: 500px;" data-bs-interval="7000">
                    <img src="{{ product.main_image.url }}" style="height: 100%; width: 100%; object-fit: contain"
                        class="d-block w-100" alt="...">
                </div>
                {% if product.image2 %}
                    <div class="carousel-item" style="height: 500px;" data-bs-interval="7000">
                        <img src="{{ product.image2.url }}" style="height: 100%; width: 100%; object-fit: contain"
                            class="d-block w-100" alt="...">
                    </div>
                {% endif %}
                {% if product.image3 %}
                    <div class="carousel-item" style="height: 500px;" data-bs-interval="7000">
                        <img src="{{ product.image3.url }}" style="height: 100%; width: 100%; object-fit: contain"
                            class=" d-block w-100" alt="...">
                    </div>
                {% endif %}
            </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators"
                data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next " type="button" data-bs-target="#carouselExampleIndicators"
                data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
            </button>
        </div>
        <div class="col-12 col-lg-6 my-1 px-4">
            <h2>About Item</h2>
            <div class="h-25 overflow-auto my-4 border-bottom">
                <p>{{ product.description }}</p>
                <small>Rating:{{ product.rating }}</small>
            </div>
            <p>£{{ product.price }}</p>
            <form class="form" action="{% url 'add_to_bag' product.id %}" method="POST">
                {% csrf_token %}
                <div class="form-row">
                    <div class="col-12">
                        {% if product.has_sizes %}
                            <div class="col-12">
                                <p><strong>Size:</strong></p>
                                <select name="product_size" id="id_product_size" class="form-control rounded-0 w-25">
                                    <option value="16gb" selected>16GB</option>
                                    <option value="32gb">32GB</option>
                                    <option value="64gb">64GB</option>
                                    <option value="128gb">128GB</option>
                                </select>
                            </div>
                        {% endif %}
                        <p class="mt-2 mb-0">Quantity:</p>
                        <div class="form-group w-25">
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <button class="decrement-qty btn button rounded-0" data-item-id="{{ product.id }}"
                                        id="decrement-qty_{{ product.id }}">
                                        <span class="icon">
                                            <i class="fas fa-minus"></i>
                                        </span>
                                    </button>
                                </div>
                                <input class="form-control qty_input" type="number"
                                            name="quantity" value="1" min="1" max="99"
                                            data-item_id="{{ product.id }}"
                                            id="id_qty_{{ product.id }}">
                                <div class="input-group-append">
                                    <button class="increment-qty btn button" data-item-id="{{ product.id }}"
                                        id="increment-qty_{{ product.id }}">
                                        <span class="icon">
                                            <i class="fas fa-plus"></i>
                                        </span>
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-12 mt-3">
                        <a href="{% url 'products' %}">
                            <span class="buttons-invt">Back</span>
                        </a>
                        <input class="shop-now-button" value="Add to bag"type="submit">
                    </div>
                    <input type="hidden" name="redirect_url" value="{{ request.path }}">
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}
{% block postloadjs %}
    {{ block.super }}
    {% include 'products/includes/quantity_input_script.html' %}
{% endblock %}

products/templates/products/products.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
<div class="container header-container">
    <div class="row">
        <div class="col">

        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
    <div class="row my-2">
        <div class="col text-center">
            <h1>Products</h1>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-6" style="color:grey;"><small class="border-bottom">Products found: {{ products|length }}</small> </div>
        <div class="sort-select-wrapper justify-content-end d-flex col-6">
            <select id="sort-selector"
                class="custom-select custom-select-sm rounded-0 border border-{% if current_sorting != 'None_None' %}info{% else %}black{% endif %}">
                <option value="reset" {% if current_sorting == 'None_None' %}selected{% endif %}>Sort by...</option>
                <option value="price_asc" {% if current_sorting == 'price_asc' %}selected{% endif %}>Price (low to high)
                </option>
                <option value="price_desc" {% if current_sorting == 'price_desc' %}selected{% endif %}>Price (high to low)
                </option>
                <option value="rating_asc" {% if current_sorting ==  'rating_asc' %}selected{% endif %}>Rating (low to
                    high)</option>
                <option value="rating_desc" {% if current_sorting == 'rating_desc' %}selected{% endif %}>Rating (high to
                    low)</option>
                <option value="name_asc" {% if current_sorting == 'name_asc' %}selected{% endif %}>Name (A-Z)</option>
                <option value="name_desc"{% if current_sorting == 'name_desc' %}selected{% endif %}>Name (Z-A)</option>
                <option value="category_asc" {% if current_sorting == 'category_asc' %}selected{% endif %}>Category (A-Z)
                </option>
                <option value="category_desc" {% if current_sorting == 'category_desc' %}selected{% endif %}>Category
                    (Z-A)</option>
            </select>
        </div>
    </div>
    <div class="row">
        {% for product in products %}
        <div class="col-lg-3 col-md-6 col-12 my-3">
            <div class="card border-bottom border-0" style="height:550px;">
                <div style="height:300px;">
                    <a href="{% url 'product_detail' product.id %}">
                        <img class="card-img-top mt-2" style="height: 100%; width: 100%; object-fit: contain" src="{{ product.main_image.url }}" alt="Card image cap">
                    </a>                    
                </div>
                <div class="card-body mt-4 py-0">
                    <a href="{% url 'product_detail' product.id %}">
                        <p class="card-text mb-0 text-black">{{ product.name }}</p>
                    </a>
                </div>
                <div class="card-footer">
                    <p class="card-text">£{{ product.price }}</p>
                    <small class="card-text mb-0">{{ product.rating }}</small>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

{% block postloadjs %}
    {{ block.super }}
    
    <script type="text/javascript">
        $('#sort-selector').change(function() {
            var selector = $(this);
            var currentUrl = new URL(window.location);

            var selectedVal = selector.val();
            if(selectedVal != "reset"){
                var sort = selectedVal.split("_")[0];
                var direction = selectedVal.split("_")[1];

                currentUrl.searchParams.set("sort", sort);
                currentUrl.searchParams.set("direction", direction);

                window.location.replace(currentUrl);
            } else {
                currentUrl.searchParams.delete("sort");
                currentUrl.searchParams.delete("direction");

                window.location.replace(currentUrl);
            }
        })
    </script>
{% endblock %}